version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.6.4
    steps:
      - run: echo <<pipeline.number>>

workflows:
  version: 2
  pipeline-test:
    jobs:
      - build:
          filters:
            branches:
              only: /.*/
            tags:
              only: /^v.*/