version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo "Hello CircleCI forked"
workflows:
  version: 2
  workflow:
   jobs:
     - build

