version: 2.1
jobs:
  build:
    parameters:
      py_version:
        type: string
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $CONTEXT_ENV
      - run: echo << parameters.py_version >>
  deploy:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run: echo $PROJECT_ENV
      
workflows:
  version: 2
  workflow:
   jobs:
     - build:
         matrix:
           parameters:
             py_version: ["3.6", "3.7", "3.8"]

         context: forked-project
     - hold:
         type: approval
         requires:
           - build
     - deploy:
         context: forked-project
         requires:
           - hold

